PetabJL integration
ICB-DCM/pyPESTO pull request #1089
Opened 2023-06-28 07:12 UTC by PaulJonasJost

2023-06-30 05:36 UTC, sebapersson requested changes
Thank you so much for working on this PEtab.jl importer :)

I have added a few comments to allow more efficient usage of the Julia PEtab importer.

2023-07-20 07:33 UTC, yannikschaelte approved these changes
would be good to be able to test precompilation too

2023-07-20 07:33 UTC, yannikschaelte commented on pypesto/objective/julia/petabJl.py
> +        # call the super super constructor
super super super

2023-07-28 16:57 UTC, dweindl commented on pypesto/objective/julia/petabJl.py
> +        Julia source file. Defaults to "{module_name}.jl".
```suggestion
        Julia source file. Defaults to "{module}.jl".
```
?

2023-07-28 16:57 UTC, dweindl commented on pypesto/objective/julia/petab_jl_importer.py
> +        source_file: str = None,
document?

2023-07-28 16:57 UTC, dweindl commented on test/julia/test_pyjulia.py
> +    yaml_file = f"doc/example/{model_name}/{model_name}.yaml"
Please use an absolute path based on `__file__` so pytest can be invoked from any directory. Also below.

2023-07-28 16:57 UTC, dweindl commented on test/julia/test_pyjulia.py
> +    optimize.minimize(problem, engine=SingleCoreEngine(), n_starts=10)
Why 10 starts if not even a single results is checked?

2023-08-08 08:07 UTC, merged