New petabjl syntax
ICB-DCM/pyPESTO pull request #1131
Opened 2023-10-10 14:02 UTC by PaulJonasJost

new example taken from [here](https://sebapersson.github.io/PEtab.jl/stable/Boehm/)

2023-10-12 08:26 UTC, sebapersson requested changes
Very minor comments. I will also try to fix the API doc in PEtab.jl to make it easy for anyone to see all the options.

2023-10-12 08:26 UTC, sebapersson commented on doc/example/conversion_reaction/PEtabJl_module.jl
>  # A full list of options for createPEtabODEProblem can be found at https://sebapersson.github.io/PEtab.jl/dev/API_choosen/#PEtab.setupPEtabODEProblem
Change to PEtabODEProblem in the coment (createPEtabODEProblem no longer exists)

2023-10-12 13:59 UTC, Doresic approved these changes
Looks good, a better naming scheme than before.

2023-10-13 12:38 UTC, PaulJonasJost commented on doc/example/conversion_reaction/PEtabJl_module.jl
>  # A full list of options for createPEtabODEProblem can be found at https://sebapersson.github.io/PEtab.jl/dev/API_choosen/#PEtab.setupPEtabODEProblem
```suggestion
# A full list of options for PEtabODEProblem can be found at https://sebapersson.github.io/PEtab.jl/stable/API_choosen/
```

2023-10-19 08:09 UTC, merged