Feature hdf5hist pj
ICB-DCM/pyPESTO pull request #564
Opened 2021-01-27 17:58 UTC by PaulJonasJost

Saving a Hdf5 History is now possible when using SingleCoreEngine. Next steps should be to be able to use it with Multiprocessing.

Replaces #267.

2021-01-27 20:32 UTC, FFroehlich commented
Thanks for taking the initiative! Nothing against more tests, but `https://github.com/ICB-DCM/pyPESTO/blob/master/test/base/test_history.py` already implements tests for history and should be straightforward to extend to hdf5.

2021-01-28 11:06 UTC, PaulJonasJost commented
in the `docs` test i get the error `/home/runner/work/pyPESTO/pyPESTO/doc/example/hdf5_storage.ipynb:document isn't included in any toctree` does anyone know what this means and how to fix it?

2021-01-28 11:24 UTC, yannikschaelte commented
> in the `docs` test i get the error `/home/runner/work/pyPESTO/pyPESTO/doc/example/hdf5_storage.ipynb:document isn't included in any toctree` does anyone know what this means and how to fix it?

This means that it is not included in the list of examples yet https://github.com/ICB-DCM/pyPESTO/blob/master/doc/example.rst and therefore not accessible in the docs. Just append it there.

2021-02-08 16:24 UTC, LeonardSchmiester approved these changes
From what I can tell, it looks good :+1:

2021-02-08 16:27 UTC, PaulJonasJost commented on pypesto/store/save_to_hdf5.py
> +                # start['history'] = None  # TOOD temporary fix
Not sure, but i think its good it is there, since otherwise it will want to write the history in result again potentially increasing the filesize?

2021-02-08 16:42 UTC, LeonardSchmiester commented on pypesto/store/save_to_hdf5.py
> +                # start['history'] = None  # TOOD temporary fix
But currently the line is commented out anyway, not?

2021-02-08 16:52 UTC, FFroehlich requested changes
Please add/remove `Hdf5History` to/from the following instance checks or completely remove them:

https://github.com/ICB-DCM/pyPESTO/blob/a34608de9ad0a274afb6fb89ebc022aff5baf4c0/test/base/test_history.py#L75

https://github.com/ICB-DCM/pyPESTO/blob/a34608de9ad0a274afb6fb89ebc022aff5baf4c0/test/base/test_history.py#L117

https://github.com/ICB-DCM/pyPESTO/blob/a34608de9ad0a274afb6fb89ebc022aff5baf4c0/test/base/test_history.py#L423

https://github.com/ICB-DCM/pyPESTO/blob/a34608de9ad0a274afb6fb89ebc022aff5baf4c0/test/base/test_history.py#L445

And add `hdf5` to 

https://github.com/ICB-DCM/pyPESTO/blob/a34608de9ad0a274afb6fb89ebc022aff5baf4c0/test/base/test_history.py#L391

2021-02-09 07:32 UTC, PaulJonasJost commented on pypesto/store/save_to_hdf5.py
> +                # start['history'] = None  # TOOD temporary fix
You are absolutely right, sorry i misread the above. Is removed.

2021-02-09 07:33 UTC, PaulJonasJost commented on pypesto/store/read_from_hdf5.py
> +                           file_name: str,
Done.

2021-02-09 08:11 UTC, PaulJonasJost commented
> Please add/remove `Hdf5History` to/from the following instance checks or completely remove them:
> 
> https://github.com/ICB-DCM/pyPESTO/blob/a34608de9ad0a274afb6fb89ebc022aff5baf4c0/test/base/test_history.py#L75
> 
> https://github.com/ICB-DCM/pyPESTO/blob/a34608de9ad0a274afb6fb89ebc022aff5baf4c0/test/base/test_history.py#L117
> 
> https://github.com/ICB-DCM/pyPESTO/blob/a34608de9ad0a274afb6fb89ebc022aff5baf4c0/test/base/test_history.py#L423
> 
> https://github.com/ICB-DCM/pyPESTO/blob/a34608de9ad0a274afb6fb89ebc022aff5baf4c0/test/base/test_history.py#L445
> 
> And add `hdf5` to
> 
> https://github.com/ICB-DCM/pyPESTO/blob/a34608de9ad0a274afb6fb89ebc022aff5baf4c0/test/base/test_history.py#L391

Thanks, changed almost all the things you mentioned. Only the third i did not remove, as when i did that 4 tests failed with the folowing message:
```
========================================================================================== short test summary info ===========================================================================================
FAILED test/base/test_history.py::test_history_properties[] - TypeError: argument of type 'ABCMeta' is not iterable
FAILED test/base/test_history.py::test_history_properties[memory] - TypeError: argument of type 'ABCMeta' is not iterable
FAILED test/base/test_history.py::test_history_properties[csv] - TypeError: argument of type 'ABCMeta' is not iterable
FAILED test/base/test_history.py::test_history_properties[hdf5] - TypeError: argument of type 'ABCMeta' is not iterable
```

2021-02-09 20:19 UTC, FFroehlich commented
> > Please add/remove `Hdf5History` to/from the following instance checks or completely remove them:
> > https://github.com/ICB-DCM/pyPESTO/blob/a34608de9ad0a274afb6fb89ebc022aff5baf4c0/test/base/test_history.py#L75
> > 
> > https://github.com/ICB-DCM/pyPESTO/blob/a34608de9ad0a274afb6fb89ebc022aff5baf4c0/test/base/test_history.py#L117
> > 
> > https://github.com/ICB-DCM/pyPESTO/blob/a34608de9ad0a274afb6fb89ebc022aff5baf4c0/test/base/test_history.py#L423
> > 
> > https://github.com/ICB-DCM/pyPESTO/blob/a34608de9ad0a274afb6fb89ebc022aff5baf4c0/test/base/test_history.py#L445
> > 
> > And add `hdf5` to
> > https://github.com/ICB-DCM/pyPESTO/blob/a34608de9ad0a274afb6fb89ebc022aff5baf4c0/test/base/test_history.py#L391
> 
> Thanks @FFroehlich, changed almost all the things you mentioned. Only the third i did not remove, as when i did that 4 tests failed with the folowing message:
> 
> ```
> ========================================================================================== short test summary info ===========================================================================================
> FAILED test/base/test_history.py::test_history_properties[] - TypeError: argument of type 'ABCMeta' is not iterable
> FAILED test/base/test_history.py::test_history_properties[memory] - TypeError: argument of type 'ABCMeta' is not iterable
> FAILED test/base/test_history.py::test_history_properties[csv] - TypeError: argument of type 'ABCMeta' is not iterable
> FAILED test/base/test_history.py::test_history_properties[hdf5] - TypeError: argument of type 'ABCMeta' is not iterable
> ```

That sounds like there is an issue that needs to be fixed. Not immediate

> > Please add/remove `Hdf5History` to/from the following instance checks or completely remove them:
> > https://github.com/ICB-DCM/pyPESTO/blob/a34608de9ad0a274afb6fb89ebc022aff5baf4c0/test/base/test_history.py#L75
> > 
> > https://github.com/ICB-DCM/pyPESTO/blob/a34608de9ad0a274afb6fb89ebc022aff5baf4c0/test/base/test_history.py#L117
> > 
> > https://github.com/ICB-DCM/pyPESTO/blob/a34608de9ad0a274afb6fb89ebc022aff5baf4c0/test/base/test_history.py#L423
> > 
> > https://github.com/ICB-DCM/pyPESTO/blob/a34608de9ad0a274afb6fb89ebc022aff5baf4c0/test/base/test_history.py#L445
> > 
> > And add `hdf5` to
> > https://github.com/ICB-DCM/pyPESTO/blob/a34608de9ad0a274afb6fb89ebc022aff5baf4c0/test/base/test_history.py#L391
> 
> Thanks @FFroehlich, changed almost all the things you mentioned. Only the third i did not remove, as when i did that 4 tests failed with the folowing message:
> 
> ```
> ========================================================================================== short test summary info ===========================================================================================
> FAILED test/base/test_history.py::test_history_properties[] - TypeError: argument of type 'ABCMeta' is not iterable
> FAILED test/base/test_history.py::test_history_properties[memory] - TypeError: argument of type 'ABCMeta' is not iterable
> FAILED test/base/test_history.py::test_history_properties[csv] - TypeError: argument of type 'ABCMeta' is not iterable
> FAILED test/base/test_history.py::test_history_properties[hdf5] - TypeError: argument of type 'ABCMeta' is not iterable
> ```

I suppose thats fine since `get_grad_trace()` is not implemented for `Hdf5History`, right?

2021-02-10 14:39 UTC, PaulJonasJost reviewed
> 
> I suppose thats fine since `get_grad_trace()` is not implemented for `Hdf5History`, right?

There is actually. Line 980+981 (sorry, could not manage to comment them).

2021-02-10 14:58 UTC, FFroehlich commented
> > I suppose thats fine since `get_grad_trace()` is not implemented for `Hdf5History`, right?
> 
> There is actually. Line 980+981 (sorry, could not manage to comment them).

You can get a link by clicking on the line number in the file view in github and then on the three dots that appear next to it.

I tried and couldn't reproduce your issue, let's see what happens on GHA.

2021-02-10 15:50 UTC, PaulJonasJost commented
> 
> 
> > > I suppose thats fine since `get_grad_trace()` is not implemented for `Hdf5History`, right?
> > 
> > 
> > There is actually. Line 980+981 (sorry, could not manage to comment them).
> 
> You can get a link by clicking on the line number in the file view in github and then on the three dots that appear next to it.
> 
> I tried and couldn't reproduce your issue, let's see what happens on GHA.

Thanks, seems to me it works :)

2021-02-10 17:19 UTC, FFroehlich approved these changes
👍

2021-02-11 07:40 UTC, merged